version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: telugu-books-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-strongpassword123}
      MONGO_INITDB_DATABASE: telugu-books
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - telugu-books-network

  # Telugu Books Application
  telugu-books-app:
    build: .
    container_name: telugu-books-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:${MONGODB_PASSWORD:-strongpassword123}@mongodb:27017/telugu-books?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your_super_secret_jwt_key_here}
      JWT_EXPIRE: 30d
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}

      # Google OAuth
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      # Razorpay
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

      # ShipRocket
      SHIPROCKET_EMAIL: ${SHIPROCKET_EMAIL}
      SHIPROCKET_PASSWORD: ${SHIPROCKET_PASSWORD}

      # Email Configuration
      EMAIL_FROM: ${EMAIL_FROM:-noreply@telugubooks.com}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - telugu-books-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: telugu-books-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - telugu-books-app
    networks:
      - telugu-books-network

volumes:
  mongodb_data:
    driver: local

networks:
  telugu-books-network:
    driver: bridge
